django/test_project/urls.py
from django.contrib import admin
from django.urls import path, include # new

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')), # new
]

homepage/urls.py
from django.urls import path, include 

from . import views

app_name = "homepage"

urlpatterns = [
	path("",views.homepage, name="homepage"), # Path to the url create account
	path("addToCart/?=id<int:item>", views.add_to_cart,name="add_to_cart"), # <indicates> pos argument
	path("orders/", views.order_page, name="orders"),
    path("search/",views.search_page, name="search"),
    path("query", views.search, name="search_query"),
    path("submitOrder/", views.submit_order, name="submit_order"),
    path("remove_from_cart/?=id<int:item>", views.remove_from_cart, name="remove_from_cart"),
    path("cart", views.cart, name="cart"),
    path("retrieveOrder/", views.retrieve_order, name="retrieve_order"),
]

test_project/urls.py
from django.contrib import admin
from django.urls import path, include 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('homepage.urls'))
]

homepage/models.py
from django.db import models

# An address, to be used by grocery stores and users for shipping alike
class Address(models.Model):
	
	class Meta:
		ordering = ['addressee']  # Order items in ascending order
		verbose_name_plural = "Addresses"


	addressee = models.CharField(max_length=50)
	street_name = models.CharField(max_length=50)
	suite = models.IntegerField(blank=True,null=True)
	city = models.CharField(max_length=20)
	state_abbreviation = models.CharField(max_length=2)
	zip_code = models.DecimalField(max_digits=5, decimal_places=0)
	Store = models.BooleanField(default=False,null=False,blank=False)
	# Addresses have many-to-one relationships with Orders and GroceryStores
	
	def __str__(self):
		return (
			self.addressee + "\n" +
			" " + self.street_name + ((", #" + str(self.suite)) if self.suite else "") + "\n" +
			self.city + ", " + self.state_abbreviation + " " + str(self.zip_code)
		)



# A grocery store connected to our website
class GroceryStore(models.Model):
	
	class Meta:
		ordering = ['name']  # Order items in ascending order
		verbose_name_plural = "Grocery Stores"

	name = models.CharField(max_length=50)
	address = models.ForeignKey(Address, 
								on_delete=models.CASCADE,
								limit_choices_to={'Store':True},)
	# GroveryStores have a many-to-one relationship with Inventory

	def __str__(self):
		return self.name



# Items are types of product like apples
class Item(models.Model):

	class Meta:
		ordering = ['name'] # Order items in ascending order

	name = models.CharField(primary_key=True,max_length=50)
	description = models.TextField(blank=True)
	# Items have a many-to-one relationship with Inventory
	
	
	def __str__(self):
		return self.name



# Inventory instances contain the price and stock for a specific Item at a specific GroceryStore
class Inventory(models.Model):
	
	class Meta:
		ordering = ['store','item']  # Order items in ascending order
		verbose_name_plural = "Inventory"
		constraints = [models.UniqueConstraint(fields=['item','store'],name='Item_Store')]

	item = models.ForeignKey(Item, on_delete=models.CASCADE)
	price = models.DecimalField(max_digits=9, decimal_places=2)
	stock = models.IntegerField()
	store = models.ForeignKey(GroceryStore, on_delete=models.CASCADE)
	# Inventory items have many-to-many relationships with Orders

	def __str__(self):
		return self.item.name + " " + self.store.name + " $" + str(self.price) + " " + str(self.stock)



# Orders placed by the customer
class Order(models.Model):
	# order_number is the "id" field which Django automatically generates
	# 
	class Meta:
		ordering = ['id']

	ordered_inventory = models.ManyToManyField(Inventory)
	date = models.DateField()
	total_price = models.DecimalField(max_digits=9, decimal_places=2)
	DELIVERY_METHODS = (
		('P', 'Pickup'),
		('D', 'Delivery') 
	)
	delivery_choice = models.CharField(max_length=1, choices=DELIVERY_METHODS)
	delivery_address = models.ForeignKey(Address, on_delete=models.CASCADE, blank=True)

	def __str__(self):
		return str(self.id)

homepage/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.exceptions import ObjectDoesNotExist
from django.contrib import messages
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import HttpResponse
from .models import Item, Inventory, Order, Address
from django.urls import reverse
import datetime

# Create your views here.

def homepage(request):

	# Setup request sessions
	# If cart/quantity does not exist since user hasn't visited, then create a new variable.
	if 'cart_id' not in request.session or 'cart_quant' not in request.session:
		# Note: Make a temporary cart object with placeholders
		request.session.flush()
		new_cart = Order(date=datetime.datetime.now(),total_price=0,
						 delivery_choice='D',delivery_address=Address.objects.all().first(),)
		new_cart.save()
		request.session['cart_id'] = new_cart.id
		request.session['cart_quant'] = {}
	

	#  Get the list of inventory items and separate them into pages
	item_list = Inventory.objects.all()
	paginator = Paginator(item_list, 15)
	page = request.GET.get('page')
	
	try:
		InventoryList = paginator.page(page)
	except PageNotAnInteger:
		InventoryList = paginator.page(1)
	except EmptyPage:
		InventoryList = paginator.page(paginator.num_pages)
	
	return render(request=request, 
				  template_name="homepage/home.html", # Where to find the html file
				  context={"Inventory":InventoryList}) # We can pass Tutorial objects via the name "tutorials"


def add_to_cart(request, item):
	
	# Add an item to the cart

	# Check if web page sent a POST request. 
	if request.POST:
		inventory_item = get_object_or_404(Inventory, pk=item) # Chooses item that was passed in
		chosen_quantity = request.POST.getlist('quantities') # Get from field quantities
		chosen_quantity = int(chosen_quantity[0])
		
		# Add to request session 'cart'
		if(chosen_quantity > 0 and inventory_item):
			
			# Retrieve cart ID and order
			# Also update quantity
			cart_id = request.session['cart_id']
			cart = Order.objects.get(id=cart_id)
			cart.ordered_inventory.add(inventory_item)
			cart_quantity = request.session['cart_quant']
			cart_quantity[inventory_item.id] = chosen_quantity
			print(cart_quantity)
			print(cart_quantity)
			request.session.modified = True
			cart.total_price += chosen_quantity * inventory_item.price
			cart.save()

			# Display to the user that the item was successfully added to the cart.
			success_string = "%d %s added to Cart" % (chosen_quantity,inventory_item.item)
			messages.success(request, success_string)
		
		else:
			# If item is not successfully added to the cart, then display that the action was invalid.
			messages.error(request, "Sorry, you can't do that")
		
		return redirect(reverse('homepage:homepage'))
	

def order_page(request):

	# Retrieve object

	cart = Order.objects.get(id=request.session['cart_id'])
	cart_items = cart.ordered_inventory.all()

	store_list = []
	for item in cart_items:
		if item.store not in store_list:
			store_list.append(item.store)
	cart_quantity = request.session['cart_quant']
	
	if len(store_list) > 1:
		messages.warning(request, "You have items in your cart that are from different stores!")

	return render(request=request,
					  template_name="homepage/orders.html",
					  context={"cart":cart, "items":cart.ordered_inventory.all(),"inventory_quantities":cart_quantity})

def submit_order(request):

	if request.POST:
		# Address:
		order_address = {}
		try:
			order_address['first_name'] = request.POST.getlist("First_Name")[0]
			order_address['last_name'] = request.POST.getlist("Last_Name")[0]
			order_address['email'] = request.POST.getlist("email")[0]
			order_address['address'] = request.POST.getlist("address")[0]
			order_address['city'] = request.POST.getlist("city")[0]
			order_address['zip_code'] = request.POST.getlist("zip_code")[0]
			order_address['country'] = request.POST.getlist("country")[0]
			order_address['state'] = request.POST.getlist("state")[0]
		except IndexError:
			messages.error(request,"Please enter everything")
			return redirect(reverse('homepage:orders'))	

		for address in order_address:
			if not order_address[address]:
				messages.error(request,"Oh no! %s is missing." % address)
				return redirect(reverse('homepage:orders'))	
		

		# Card information
		card_info = {}
		card_info['card_name']= request.POST.getlist("name_on_card")[0]
		card_info['card_month'] = request.POST.getlist("month")[0]
		card_info['card_year']= request.POST.getlist("year")[0]

		for info in card_info:
			if not card_info[info]:
				messages.error(request,"Oh no! %s is missing." % info)
				return redirect(reverse('homepage:orders'))		

		# Shipping Information
		shipping = request.POST.getlist("shipping_button")
		final_shipping = {}
		if not shipping:
			final_shipping['first_name'] = request.POST.getlist("First_Name")[0]
			final_shipping['last_name'] = request.POST.getlist("Last_Name")[0]
			final_shipping['email'] = request.POST.getlist("email")[0]
			final_shipping['address']= request.POST.getlist("address")[0]
			final_shipping['city'] = request.POST.getlist("city")[0]
			final_shipping['zip_code'] = request.POST.getlist("zip_code")[0]
			final_shipping['country'] = request.POST.getlist("country")[0]
			final_shipping['state'] = request.POST.getlist("state")[0]
		else:
			final_shipping = order_address
		
		current_cart = Order.objects.get(id=request.session['cart_id'])
		
		if request.POST.getlist("Delivery")[0] == 'D':
			current_cart.delivery_choice = request.POST.getlist("Delivery")[0]
			current_cart.total_price += 5

		cart_quantity = request.session['cart_quant']
		
		for items in cart_quantity.keys():
			print(items)
			current_inventory = current_cart.ordered_inventory.get(id=str(items))		
			if current_inventory:
				# Check if item exists, otherwise send an error message
				if current_inventory.stock - cart_quantity[items] < 0:
					# Check if user is trying to buy more than what is in stock
					messages.error(request, "I'm sorry, there's not enough %s in stock." % current_inventory.item)
					return redirect(reverse('homepage:orders'))
				else:
					current_inventory.stock -= cart_quantity[items]
					current_inventory.save()
			else:
				messages.error(request, "Oh no! The item was deleted from inventory");
				return redirect(reverse('homepage:orders'))
		

		current_cart.date = datetime.datetime.now()
		new_address = Address(addressee=final_shipping['first_name'] + " " + final_shipping['last_name'],
												street_name=final_shipping['address'],
												city=final_shipping['city'],
												state_abbreviation=final_shipping['state'],
												zip_code=final_shipping['zip_code'],)
		new_address.save()
		
		current_cart.delivery_address = new_address
		current_cart.delivery_address.save()
		current_cart.save()

		messages.success(request, "Order successfully entered. Confirmation Number #%d" % request.session['cart_id'])
		request.session.flush()
		
		
	return redirect(reverse('homepage:homepage'))




def search_page(request):

	# Render page where users can search for items
	return render(request=request,
				  template_name="homepage/search.html",
				 )

def search(request):

	# Retrieve what items what searched for in search page

	if request.GET:		
		search_item = request.GET.getlist("search") 
		search_string = search_item[0] # Retrieve the string that was searched

		# Retrieve the list of objects that contain the search string
		found_items = Inventory.objects.filter(item__name__icontains=search_string)


		if found_items:
			# If an item is found then redirect to a page with the list of items
			# that contained the search string
			return render(request=request, 
				  template_name="homepage/searchlist.html", # Where to find the html file
				  context={"Inventory":found_items}) 
		else:
			# If item is not found, then redirect back to the search page and output
			# The item was not found
			messages.error(request, "Item: %s not found" % search_string)
			return redirect(reverse('homepage:search'))

def cart(request):
	currentCart = Order.objects.get(id=request.session['cart_id'])
	items = currentCart.ordered_inventory.all()

	return render(request = request, 
                  template_name="homepage/cart.html",
                  context={"items":currentCart.ordered_inventory.all(),
				  		   "inventory_quantities":request.session['cart_quant'],
						   "cart_total":currentCart.total_price})

def remove_from_cart(request, item):
	inventory_item = get_object_or_404(Inventory, pk=item)
	cart_id = request.session['cart_id']
	cart = Order.objects.get(id=cart_id)
	quant_dictionary = request.session['cart_quant']
	item_quantity = quant_dictionary[str(inventory_item.id)]

	cart.total_price -= inventory_item.price * item_quantity
	del request.session['cart_quant'][str(inventory_item.id)]
	request.session.modified = True
	cart.ordered_inventory.remove(inventory_item)
	cart.save()

	return redirect(reverse('homepage:cart'))

def retrieve_order(request):
	try:
		order_number = Order.objects.get(id=request.GET.getlist("confirmation")[0])
	except Order.DoesNotExist:
		messages.error(request,"I'm sorry that order number doesn't exist.")
		return redirect(reverse('homepage:orders'))

	cart_list = order_number.ordered_inventory.all()

	store_list = []
	
	for item in cart_list:
		if item.store not in store_list:
			store_list.append(item.store)

	return render(request=request,
				  template_name="homepage/order_page.html",
				  context={"order" : order_number,"items": cart_list,"stores" : store_list})

homepage/templates/homepage/orders.html
<!DOCTYPE html>

<meta charset="UTF-8">

<html>
{% load static %}
{% load shopping_extras %}

<head>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	<link rel="shortcut icon" type="image/png" href="{% static '/login_app/images/favicon.ico' %}" />
	<link href='{% static "/login_app/style.css" %}' rel='stylesheet' type='text/css'>

	<!-- Compiled and minified JavaScript -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.js"></script>

	<script>

		$(document).ready(function(){
			$('select').formSelect();
			

			$('.sidenav').sidenav();

			$("#close").click(function(){
				$("#pop-up").toggle();
			});



			$("#shipping_button").click(function(){
				$("#shipping_address").attr("disabled",this.checked);
				$("#shipping_City").attr("disabled",this.checked);
				$("#shipping_zip_code").attr("disabled",this.checked);
				$("#shipping_State").attr("disabled",this.checked);
				$('#shipping_country').formSelect();
				$("#shipping_country").attr("disabled",!this.checked);
			});

		 });
		  
	</script>
</head>

<body id="custombg">
	<!-- Navigation Bar -->
	<nav>
		<div class="nav-wrapper">
			<a href="/homepage" class="brand-logo" style="padding-left: 5px">Grocery Shopping</a>

			<!-- Target for the hamburger drop down menu when it's made too small-->
			<a href="#" data-target="nav-mobile" class="sidenav-trigger"><i class="material-icons">menu</i></a>


			<ul class="right hide-on-med-and-down">
				<li><a href="/">Item Browser</a></li>
				<li><a href="/search/"><i class="material-icons prefix">search</i></a></li>
				<li><a href="/orders"><i class="material-icons">monetization_on</i></a></li>
				<li><a href="/cart"><i class="material-icons">shopping_basket</i></a></li>
				<li><a id="darkbutton"><i class="material-icons">brightness_3</i></a></li>
			</ul>

			


		</div>

		<!--Pop-up Bar when the browser is made too small -->
		<ul class="sidenav" id="nav-mobile">
			<li><a href="#">Item Browser</a></li>
			<li><a href="/orders">Cart</a></li>
		</ul>
	</nav>		

	

	


	<!-- Main Page -->
	<div class="container" id="browserBody" style="background-color: white">
		{% if messages %}
			<ul class="collection" id="pop-up">
			{% for message in messages %}
				{% if message.tags == "success" %}
					<li class=" green accent-3 collection-item center-align">{{ message }}
						<a class="btn-flat waves-effect right-align" id="close">
							<i class="material-icons">close</i>
						</a>
					</li>
				{% elif message.tags == "warning" %}
					<li class=" amber lighten-1 collection-item center-align">{{ message }}
						<a class="btn-flat waves-effect right-align" id="close">
							<i class="material-icons">close</i>
						</a>
					</li>
				{% else %}
					<li class=" red accent-2 collection-item center-align">{{ message }}
						<a class="btn-flat waves-effect right-align" id="close">
							<i class="material-icons">close</i>
						</a>
					</li>
				{% endif %}
			{% endfor %}
			</ul>
		{% endif %}
		
		<div class="card">
			<div class="row">
				<div class="col s12">
			Find previous order:
			<div class="input-field inline">
			<form method="get" action="{% url 'homepage:retrieve_order' %}">
            <input id="conf_numb" name="confirmation" placeholder="Confirmation #" type="text" class="validate">
            </form>
          </div>
				</div>
			</div>
		</div>
		<div class="card">
			<div class="row">
				<div class="col s12">
					<div class="col s12">
						<h1>Checkout Form</h1>
					</div>
				</div>
			</div>
			

			<form name="checkout_form" action="{% url 'homepage:submit_order' %}" method="post">
				{% csrf_token %}
				<div class="row">	
					<div class="col s8">
						<div class="input-field col s6">
							<input type="text" id="First_Name" name="First_Name">
							<label for="First_Name">First Name</label>
						</div>
						<div class="input-field col s6">
							<input type="text" id="Last_Name" name="Last_Name">
							<label for="Last_Name">Last Name</label>
						</div>
					</div>
				</div>
				
				<div class="row">
					<div class="col s8">
						<div class="input-field col s12">
							<input id="email" type="text" class="validate" name="email">
							<label for="email">Email Address</label>
						</div>
					</div>
				</div>

				<div class="row">
					<div class="col s12">
					<div class="input-field col s4">
							<input name="address" id="address" type="text" class="validate" >
							<label for="address">Address</label>
						</div>
						<div class="input-field col s4">
							<input name= "city" id="city" type="text" class="validate" pattern="[a-Z]">
							<label for="city">City</label>
						</div>
						<div class="input-field col s2">
							<input name="zip_code" id="zip_code" type="text" class="validate" pattern="[0-9]{5}">
							<label for="zip_code">Zip Code</label>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col s12">
						<div class="input-field col s4">
								<select name="country">
									<option value="USA">United States of America</option>
									<option value="CANADA">Canada</option>
									<option value="MEXICO">Mexico</option>
								</select>
								<label>Country/Region</label>
						</div>
						<div class="input-field col s4">
							<input name="state" id="State" type="text" pattern="[A-Z]{2}">
							<label for="State">State/Province/Region</label>
						</div>
					</div>
				</div>


				<div class="row">
					<div class="col s12">
						<div class="col s12">
							<h4>Card Information</h4>
						</div>
					</div>
				</div>

				<div class="row">
					<div class="col s12">
						<div class="input-field col s4">
							<input name="name_on_card" id="Name_On_Card" type="text" class="validate">
							<label for="Name_On_Card">Name on Card </label>
						</div>
						<div class="input-field col s4">
							<input name="card_number" id="Card_Number" type="text" class="validate">
							<label for="Card_Number">Card Number </label>
						</div>
						<div class="input-field col s1">
							<select name="month">
								{% for m in 1|card_month %}
									<option value={{m}}>{{m}}</option>
								{% endfor %}
							</select>
							<label class="center-align">MM</label>
						</div>
						<div class="input-field col s1">
							<select name="year">
								{% for y in 2030|card_year %}
									<option value="{{y}}">{{y}}</option>
								{% endfor %}
							</select>
							<label class="center-align">YYYY</label>
						</div>
					</div>
				</div>

				<div class="row">
					<div class="col s12">
						<div class="col s12">
							<h4>Shipping Information</h4>
						</div>
					</div>
				</div>

				
				<div class="row">
					<div class="col s12">
						<div class="col s6">
							<label>
								<input type="checkbox" id="shipping_button" name="shipping_button" value="1">
								<span>Same As Billing Address</span>
							</label>
						</div>
					</div>
				</div>

				<div class="row">
					<div class="col s12">
					<div class="input-field col s4" disabled >
							<input name="shipping_address" id="shipping_address" type="text" class="validate">
							<label for="shipping_address">Address</label>
						</div>
						<div class="input-field col s4">
							<input name="shipping_City" id="shipping_City" type="text" class="validate" pattern="[a-Z]">
							<label for="shipping_City">City</label>
						</div>
						<div class="input-field col s2">
							<input name="shipping_zip_code" id="shipping_zip_code" type="text" class="validate" name="shipping_zip_code" pattern="[0-9]{5}">
							<label for="shipping_zip_code">Zip Code</label>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col s12">
						<div class="input-field col s4">
								<select name="shipping_country" id="shipping_country" name="shipping_country">
									<option value="USA">United States of America</option>
									<option value="CANADA">Canada</option>
									<option value="MEXICO">Mexico</option>
								</select>
								<label>Country/Region</label>
						</div>
						<div class="input-field col s4">
							<input name="shipping_State" id="shipping_State" type="text">
							<label for="shipping_State">State/Province/Region</label>
						</div>
					</div>
				</div>

				<div class="row">
					<div class="col s12">
						<div class="col s3">
							<h4>Delivery Method</h4>
								<p>
									<label>
									  <input class="with-gap" name="Delivery" type="radio" value="D" checked />
									  <span>Delivery +$5.00</span>
									</label>
								</p>
								<p>
									<label>
									  <input class="with-gap" name="Delivery" type="radio" value="P" checked />
									  <span>Pickup</span>
									</label>
								</p>
						</div>
					</div>
				</div>

				<div class="row">
					<div class="col s12">
						<div class="col s12">
							<h4>Order Total: {{cart.total_price}}</h4>
						</div>	
					</div>
					<div class="row">
					</div>
					<div class="row">
					</div>
					<div class="col s12">
						<div class="col s12">
						<button class="btn waves-effect waves-light" type="submit">Submit
				    	<i class="material-icons right">send</i>
				 		 </button>
				 		</div>
				 	</div>
					<div class="row">
					</div>
					<div class="row">
					</div>
				</div>

				
			</form>


			
	</div>
</body>

homepage/templates/homepage/register.html
<!DOCTYPE html>

<meta charset="UTF-8">

<html>
	{% load static %}

	<head>
	  <!-- Compiled and minified CSS -->
	    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

	    <link href='{% static "/login_app/style.css" %}' rel='stylesheet' type='text/css'>

	    <!-- Compiled and minified JavaScript -->
	    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
	</head>

	<body>
		<div class="container">
			<div class="row">
				<h3 class="center-align">Grocery Store App</h3>
				<h2 class="center-align">Registration</h2>
			</div>
			<form action="post">
				<div class="row">
					<div class="input-field col s3 offset-s3">
			          <input id="first_name" type="text" class="validate">
			          <label for="first_name">First Name</label>
		       		</div>
			        <div class="input-field col s3">
			          <input  id="last_name" type="text" class="validate">
			          <label for="last_name">Last Name</label>
			        </div>
			    </div>
			    <div class="row">
			    	<div class="input-field col s6 offset-s3">
			    		<input type="text" class="datepicker"  id="birthdate">
			    		<label for="birthdate">Birthdate</label>
			    	</div>
			    </div>
			     <div class="row">
			    	<div class = "input-field col s6 offset-s3">
						<input id="email" type="email" class="validate">
						<label for="email">Email</label>
					</div>
				</div>
			    <div class="row">
			        <div class="col s6 offset-s3 center-align">
			          <button class="btn waves-effect waves-light center-align btn-large" type="submit" name="createAcc">Create Account</button>
			        </div>
			    </div>
			</form>

		</div>
	</body>
</html>

homepage/templates/homepage/search.html
<!DOCTYPE html>

<meta charset="UTF-8">

<html>
{% load static %}
{% load shopping_extras %}

<head>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	<link rel="shortcut icon" type="image/png" href="{% static '/login_app/images/favicon.ico' %}" />
	<link href='{% static "/login_app/style.css" %}' rel='stylesheet' type='text/css'>

	<!-- Compiled and minified JavaScript -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.js"></script>

	<script>

		$(document).ready(function(){
			$('select').formSelect();

	
			$('.sidenav').sidenav();


	
			$("#darkbutton").click(function(){
				$('.items').each(function(i,obj){
					$(this).toggleClass('blue-grey darken-4 darkmode');
				});

				$('.pageli').toggleClass('blue-grey darken-4 darkmode');
				$('#page_n').toggleClass('darkmode');
				$('.inactive_pages').each(function(i,obj){
					$(this).toggleClass('darkmode');
				});
			}); 

			$("#close").click(function(){
				$("#pop-up").toggle();
			});
		 });
		  
	</script>
</head>

<!-- Main Body -->
<body id="custombg">
	<!-- Navigation Bar -->
	<nav>
		<div class="nav-wrapper">
			<a href="/homepage" class="brand-logo" style="padding-left: 5px">Grocery Shopping</a>

			<!-- Target for the hamburger drop down menu when it's made too small-->
			<a href="#" data-target="nav-mobile" class="sidenav-trigger"><i class="material-icons">menu</i></a>


			<ul class="right hide-on-med-and-down">
				<li><a href="/">Item Browser</a></li>
				<li><a href="/search/"><i class="material-icons prefix">search</i></a></li>
				<li><a href="/orders"><i class="material-icons">monetization_on</i></a></li>
				<li><a href="/cart"><i class="material-icons">shopping_basket</i></a></li>
				<li><a id="darkbutton"><i class="material-icons">brightness_3</i></a></li>
			</ul>

			


		</div>

		<!--Pop-up Bar when the browser is made too small -->
		<ul class="sidenav" id="nav-mobile">
			<li><a href="#">Item Browser</a></li>
			<li><a href="/orders">Cart</a></li>
		</ul>
	</nav>		




	<!-- Main Page -->
	<div class="container">
		{% if messages %}
			<ul class="collection" id="pop-up">
			{% for message in messages %}
				{% if message.tags == "success" %}
					<li class=" green accent-3 collection-item center-align">{{ message }}
						<a class="btn-flat waves-effect right-align" id="close">
							<i class="material-icons">close</i>
						</a>
					</li>
				{% else %}
					<li class=" red accent-2 collection-item center-align">{{ message }}
						<a class="btn-flat waves-effect right-align" id="close">
							<i class="material-icons">close</i>
						</a>
					</li>
				{% endif %}
			{% endfor %}
			</ul>
		{% endif %}
		<div class="row" style="background-color: white">
			<form action="{% url 'homepage:search_query' %}" method="get">
				<div class="input-field">
					<div class="input-field col s12">
						<i class="material-icons prefix">search</i>
				        <input name="search" id="Search" type="search" class="validate">
			        </div>
				</div>
			</form>
		</div>
	</div>
</body>

</html>